In [2]:
import pandas as pd
import numpy as np

In [4]:
csv_file_path = r'C:\Users\gijsv\OneDrive\Documenten\Ironhack\week3\project\Data\Education\OUP_long_MF2564_v1.csv'

df_original = pd.read_csv(csv_file_path)
df_edu = df_original.copy()
df_edu = df_edu[df_edu['year'] >= 1980]
df_edu['year'].unique()
#df_edu['country'].unique()

array([1870, 1875, 1880, 1885, 1890, 1895, 1900, 1905, 1910, 1915, 1920,
       1925, 1930, 1935, 1940, 1945, 1950, 1955, 1960, 1965, 1970, 1975,
       1980, 1985, 1990, 1995, 2000, 2005, 2010], dtype=int64)

In [36]:
df_edu

,BLcode,WBcode,region_code,country,year,sex,agefrom,ageto,lu,lp,lpc,ls,lsc,lh,lhc,yr_sch,yr_sch_pri,yr_sch_sec,yr_sch_ter,pop
22,131,AUS,Advanced Economies,Australia,1980,MF,25,64,0.9,6.9,3.5,69.7,51.5,22.5,14.6,11.00,5.84,4.42,0.74,6978
23,131,AUS,Advanced Economies,Australia,1985,MF,25,64,1.0,7.1,3.4,66.1,52.1,25.7,16.6,11.30,5.82,4.63,0.85,7709
24,131,AUS,Advanced Economies,Australia,1990,MF,25,64,1.1,7.9,3.7,63.2,52.9,27.8,18.1,11.52,5.81,4.79,0.92,8563
25,131,AUS,Advanced Economies,Australia,1995,MF,25,64,1.1,8.2,4.0,61.6,54.0,29.1,19.0,11.72,5.81,4.95,0.96,9283
26,131,AUS,Advanced Economies,Australia,2000,MF,25,64,0.9,8.7,4.5,63.5,57.7,26.9,17.6,11.64,5.82,4.93,0.89,10092
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2576,47,ZWE,Sub-Saharan Africa,Zimbabwe,1990,MF,25,64,18.5,54.4,21.9,21.7,13.3,5.4,3.5,4.89,3.26,1.45,0.18,3242
2577,47,ZWE,Sub-Saharan Africa,Zimbabwe,1995,MF,25,64,14.1,47.6,21.5,34.8,16.8,3.5,2.3,5.70,3.64,1.94,0.12,3692
2578,47,ZWE,Sub-Saharan Africa,Zimbabwe,2000,MF,25,64,10.5,40.9,20.4,46.8,9.2,1.7,1.1,6.17,3.96,2.16,0.06,3914
2579,47,ZWE,Sub-Saharan Africa,Zimbabwe,2005,MF,25,64,7.7,36.6,19.7,54.3,8.9,1.4,0.9,7.02,4.72,2.25,0.05,4050
2580,47,ZWE,Sub-Saharan Africa,Zimbabwe,2010,MF,25,64,6.4,33.7,20.4,58.9,8.0,1.1,0.7,7.60,5.30,2.26,0.04,4407